---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: terra-aws-ec2
spec:
  interval: 1m
  url: https://github.com/prajyot-narulkar925/terraform-aws-ec2
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: terra-ec2
spec:
  path: ./terraform
  approvePlan: auto
  interval: 1m
  varsFrom:
  - kind: Secret
    name: aws-credentials
  sourceRef:
    kind: GitRepository
    name: aws-ec2
